### ISSUE TITLE
Query data error while we are building this sample

### ISSUE THREAD

**Issue by cpalanisamy** [aws-samples/aws-iot-twinmaker-samples#71] opened 2022-06-16 18:44 UTC
Hi Team,
We had set up the CookieFactory sample to explore the Twinmaker. Since yesterday, we have started to see Query Data error on the Alarms List panel on the CookieFactory AWS Managed Grafana Dashboard. We have tried multiple ways to debug this issue and we need the experts to support us here.
![Error](https://user-images.githubusercontent.com/54530458/174142829-37445167-791c-41c5-9007-3c706ae8c27a.png)

Can someone help us on this issue to proceed further?

Update: When we tried with a local instance of grafana. We see the below error in the log.   

```
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T09:30:52.699790656Z level=error msg="Query data error" error="failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=103.210.207.111 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T09:30:52.700484991Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=103.210.207.111 time_ms=909 duration=909.577838ms size=75 referer="http://local:3000/d/FTW3SQj7k/testing-twinmaker-integration?orgId=1&editPanel=2" traceID=00000000000000000000000000000000
logger=plugin.grafana-iot-twinmaker-datasource t=2022-06-17T09:30:53.333277278Z level=info msg=Profiler enabled=false
```

Thanks,
Palani

**Comment by cpalanisamy** [comment] 2022-06-18 05:51
> na Dashboard. We have tried multiple ways to debug this issue and we need the experts to support us here.

Sure, Steve. We are kind of blocked with this issue. Appreciate your support on this issue.

Regards,
Palani

**Comment by cpalanisamy** [comment] 2022-06-18 05:52
> Hi @cpalanisamy , thanks for reaching out to us. We are actively working on this issue. We will update this thread once we have more information.

Sure, Steve. We are kind of blocked with this issue. Appreciate your support on this issue.

Regards,
Palani

**Comment by stevenhy** [comment] 2022-06-21 00:27
Hi Palani, we have identified a fix for this issue. We plan to have the deployment done by early 6/22. Will update the thread once it finishes. Which AWS region do you mainly use for testing? 

Thanks.

**Comment by cpalanisamy** [comment] 2022-06-21 04:51
> Hi Palani, we have identified a fix for this issue. We plan to have the deployment done by early 6/22. Will update the thread once it finishes. Which AWS region do you mainly use for testing?
> 
> Thanks.

Hi Steve, Thanks for the response. I am using US-EAST-1 as the default region.

Thanks,
Palani

**Comment by stevenyang-aws** [comment] 2022-06-22 02:56
Could you verify if the issue is resolved in us-east-1? Thank you!

**Comment by cpalanisamy** [comment] 2022-06-22 04:13
> Could you verify if the issue is resolved in us-east-1? Thank you!

Hi Steve, I can confirm that the issue is fixed in us-east-1. Just to be curious, may I know the cause for this issue?

Thanks & Regards,
Palani

**Closed** 2022-06-22 17:41 UTC
